######################################################################
##
## Filename: tb_RS232Rxd.udo
## Created on: Thu Oct 24 1:55:19 PM Malay Peninsula Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
